# Generated by Django 4.2.8 on 2023-12-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='scale',
            field=models.CharField(choices=[('EN', 'Encounter'), ('SE', 'Settlement'), ('PR', 'Province'), ('KI', 'Kingdom'), ('CO', 'Continent')], default='EN', max_length=2),
        ),
    ]
