# Generated by Django 4.2.8 on 2024-01-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0003_map_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoiOnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.map')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.pointofinterest')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='parent_maps',
            field=models.ManyToManyField(related_name='parent_maps', through='worldbuilder.PoiOnMap', to='worldbuilder.map'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='poi_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poi_map', to='worldbuilder.map'),
        ),
    ]
