# Generated by Django 4.2.9 on 2024-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0005_alter_pointofinterest_parent_maps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.png', upload_to='thumbnails/'),
        ),
    ]
