# Generated by Django 4.2.9 on 2024-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0006_pointofinterest_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpeg', upload_to='thumbnails/'),
        ),
    ]
