# Generated by Django 4.2.9 on 2024-01-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0007_alter_pointofinterest_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'verbose_name': 'Point of Interest', 'verbose_name_plural': 'Points of Interest'},
        ),
    ]
