# Generated by Django 4.2.9 on 2024-01-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0008_alter_pointofinterest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='factions/')),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True, verbose_name='General Description')),
                ('goals', models.TextField(null=True, verbose_name='Goals')),
                ('typical_alignments', models.TextField(verbose_name='Typical Member Alignments')),
                ('typical_classes', models.TextField(verbose_name='Typical Member Classes')),
                ('typical_activities', models.TextField(verbose_name='Typical Member Activities')),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
            },
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='npcs/')),
                ('alignment', models.TextField(verbose_name='Alignment')),
                ('classes', models.TextField(verbose_name='Classes')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('goals', models.TextField(null=True, verbose_name='Individual Goals')),
                ('points_of_interest', models.ManyToManyField(to='worldbuilder.pointofinterest', verbose_name='Points of Interest')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='quests/')),
                ('description', models.TextField(verbose_name='Description')),
                ('rewards', models.TextField(blank=True, null=True, verbose_name='Rewards')),
                ('faction', models.ManyToManyField(to='worldbuilder.faction', verbose_name='Quest Faction')),
                ('quest_giver', models.ManyToManyField(to='worldbuilder.npc', verbose_name='Quest Giver')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
            },
        ),
        migrations.CreateModel(
            name='QuestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('criteria', models.TextField(verbose_name='Description')),
                ('complete', models.BooleanField(verbose_name='Complete')),
                ('points_of_interest', models.ManyToManyField(to='worldbuilder.pointofinterest', verbose_name='Points of Interest')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='worldbuilder.quest')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founded_factions', to='worldbuilder.npc', verbose_name='Founder'),
        ),
        migrations.AddField(
            model_name='faction',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader_of_factions', to='worldbuilder.npc', verbose_name='Leader'),
        ),
        migrations.AddField(
            model_name='faction',
            name='notable_members',
            field=models.ManyToManyField(related_name='factions', to='worldbuilder.npc', verbose_name='Notable Members'),
        ),
        migrations.AddField(
            model_name='faction',
            name='points_of_interest',
            field=models.ManyToManyField(to='worldbuilder.pointofinterest', verbose_name='Points of Interest'),
        ),
    ]
