# Generated by Django 4.2.9 on 2024-01-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0009_faction_npc_quest_questtask_faction_founder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='General Description'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='founded_factions', to='worldbuilder.npc', verbose_name='Founder'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Goals'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader_of_factions', to='worldbuilder.npc', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='typical_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Typical Member Activities'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='typical_alignments',
            field=models.TextField(blank=True, null=True, verbose_name='Typical Member Alignments'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='typical_classes',
            field=models.TextField(blank=True, null=True, verbose_name='Typical Member Classes'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='alignment',
            field=models.TextField(blank=True, null=True, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='classes',
            field=models.TextField(blank=True, null=True, verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Individual Goals'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='image',
            field=models.ImageField(null=True, upload_to='npcs/'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpeg', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.ImageField(null=True, upload_to='quests/'),
        ),
        migrations.AlterField(
            model_name='questtask',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='questtask',
            name='criteria',
            field=models.TextField(blank=True, null=True, verbose_name='Criteria'),
        ),
    ]
