# Generated by Django 4.2.9 on 2024-01-23 18:30

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0013_pointofinterest_description_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='description_rendered', verbose_name='General Description'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='description_rendered', verbose_name='Description'),
        ),
    ]
