# Generated by Django 4.2.9 on 2024-01-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0015_faction_description_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='description_new',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
