# Generated by Django 4.2.9 on 2024-01-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0016_alter_faction_description_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map_name',
            new_name='name',
        ),
    ]
