# Generated by Django 4.2.9 on 2024-02-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0017_rename_map_name_map_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='description_new',
        ),
    ]
