# Generated by Django 4.2.9 on 2024-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0019_ensure_rendered_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='points_of_interest',
            field=models.ManyToManyField(blank=True, to='worldbuilder.pointofinterest', verbose_name='Points of Interest'),
        ),
    ]
